const regions = [
  { value: 'Minas Tirith / 미나스 티리스', coords:[2450.0072, 1962.575] },
  { value: 'Osgiliath / 오스길리아스', coords:[2486.7017, 1989.8004] },
  { value: 'Minas Morgul / 미나스 모르굴', coords:[2547.0702, 1982.6981] },
  { value: 'Edoras / 에도라스', coords:[1878.2828, 1732.935] },
  { value: 'Anorien / 아노리엔', coords:[2292.5758, 1896.2872] },
  { value: 'Eastfold / 이스트폴드', coords:[2016.775, 1796.8554] },
  { value: `Helm's Deep / 헬름 협곡`, coords:[1785.9546, 1695.0562] },
  { value: 'Lothlorien / 로스로리엔', coords:[1987.1827, 1189.6115] },
  { value: 'Rivendell / 리븐델', coords:[1848.8328, 746.6704]},
  { value: 'Isengard / 아이센가드', coords:[1688.3238, 1520.8176] },
  { value: 'Black Gate / 블랙 게이트', coords:[2601.6625, 1712.5789] },
  { value: 'Dol Guldur / 돌 굴두르', coords:[2243.7133, 1148.6588]},
  { value: 'Mordor / 모르도르', coords:[3083.7443, 2053.4878] },
  { value: 'Gondor / 곤도르', coords:[1918.0567, 2043.0859] },
  { value: 'Rohan / 로한', coords:[1970.1393, 1557.7642] },
  { value: 'White Mountains / 백색 산맥', coords:[1790.2177, 1820.5481] },
  { value: 'Ithilien / 이실리엔', coords:[2505.1692, 1830.0178] },
  { value: 'Anduin / 안두인', coords:[2142.9587, 1036.9312] },
  { value: 'Annuminas / 안누미나스', coords:[1014.1811, 606.6336] },
  { value: 'Misty Mountains / 안개 산맥', coords:[1930.3607, 805.4971] },
  { value: 'Angmar / 앙그마르', coords:[1692.4381, 196.4776] },
  { value: 'Barad Dur / 바랏 두르', coords:[2828.7848, 1883.2664]},
  { value: 'Mirkwood / 어둠 숲', coords:[2603.291, 952.8692] },
  { value: 'Pelargir / 펠라르기르', coords:[2379.5728, 2286.3201] },
  { value: 'Lonely Mountain / 외로운 산', coords:[2550.2384, 473.4328] },
  { value: 'Arthedain / 아르세다인', coords:[992.0229, 668.0349] },
  { value: 'Rhudaur / 루다우르', coords:[1740.5913, 641.0463] },
  { value: 'Cardolan / 카르돌란', coords:[1274.6892, 1016.0461] },
  { value: 'Ephel Duath / 에펠 두아스', coords:[2612.1687, 2217.073] },
  { value: 'Lindon / 린돈', coords:[250.0046, 640.3694] },
  { value: 'Fornost Erain / 포르노스트 에라인', coords:[1255.0694, 574.7511] },
  { value: 'Belfalas / 벨팔라스', coords:[1881.353, 2315.3395] },
  { value: 'Rhovanion / 로바니온', coords:[2694.5511, 1321.0219] },
];

export const sortedRegions = regions.sort((a, b) => a.value.localeCompare(b.value));

// export const pages = [
//   { value: 'westron' },
//   { value: 'sindarin' },
//   { value: 'khuzdul' },
//   { value: 'black speech' },
//   { value: 'aduanic' },
//   { value: 'quenya' },
//   { value: 'telerin' },
//   { value: 'men' },
//   { value: 'elf' },
//   { value: 'dwarf' },
//   { value: 'hobbit' },
//   { value: 'orc' },
//   { value: 'barlog' },
//   { value: 'dragon' },
//   { value: 'ainur' },
//   { value: 'Rohirrim' },
//   { value: 'Gondorians' },
//   { value: 'Numenorians' },
//   { value: 'Arnorians' },
//   { value: 'Dalesmen' },
//   { value: 'Noldor' },
//   { value: 'Sindar' },
//   { value: 'Teleri' },
//   { value: 'Silvan' },
//   { value: 'LongBeards' },
//   { value: 'Firebeards' },
//   { value: 'Broadbeams' },
//   { value: 'Ironfists' },
//   { value: 'Mordor-Orc' },
//   { value: 'Misty-Mountain-Orc' },
//   { value: 'Moria-Orc' },
//   { value: 'Harfoots' },
//   { value: 'Stoors' },
//   { value: 'Fallohides' },
//   { value: 'Valar' },
//   { value: 'Maiar' },
//   { value: 'Minas-Tirith' },
//   { value: 'Edoras' },
//   { value: `Helm's-Deep` },
//   { value: 'Osgilath' },
//   { value: 'Angmar' },
//   { value: 'Mount-Gundabasd' },
//   { value: 'Tolfalas' },
//   { value: 'Dol-Guldur' },
//   { value: 'Hills-of-Evendim' },
//   { value: 'Weathertop' },
//   { value: 'Lindon' },
//   { value: 'Rivendell' },
//   { value: 'Erebor' },
//   { value: 'Shire' },
//   { value: 'Numenor' },
//   { value: 'Havens-of-Sirion' },
//   { value: 'Rohan' },
//   { value: 'Lothlorien' },
//   { value: 'Valinor' },
//   { value: 'The-Woodland-Realm' },
//   { value: 'Gondolin' },
//   { value: 'Hobbiton' },
//   { value: 'Isengard' },
//   { value: 'Bree' },
//   { value: 'Carn-Dum' },
//   { value: 'Iron-Hills' },
//   { value: 'Lake-Town' },
//   { value: 'Fangorn' },
//   { value: 'Barad-dûr' },
//   { value: 'Minas-Morgul' },
//   { value: 'Arnor' },
//   { value: 'Moria' },
//   { value: 'Aragorn-II' },
//   { value: 'Arwen-Undomiel' },
//   { value: 'Boromir' },
//   { value: 'Faramir' },
//   { value: 'Denethor II' },
//   { value: 'Theoden' },
//   { value: 'Gimli' },
//   { value: 'Frodo-Baggins' },
//   { value: 'Gandalf' },
//   { value: 'Elendil' },
//   { value: 'Isildur' },
//   { value: 'Elrond' },
//   { value: 'Eomer' },
//   { value: 'Haldir' },
//   { value: 'Galadriel' },
//   { value: 'Celeborn' },
//   { value: 'Sauron' },
//   { value: 'Melkor' },
//   { value: 'Azog' },
//   { value: 'Legolas' },
//   { value: 'Thranduil' },
//   { value: 'Eärendil' },
//   { value: 'Elros' },
//   { value: 'Thorin-II' },
//   { value: 'Eowyn' },
//   { value: 'Grima' },
//   { value: 'Theodred' },
//   { value: 'King-Helm' },
//   { value: 'Eorl' },
//   { value: 'Witch-King-of-Angmar' },
//   { value: 'Balin' },
//   { value: 'Dwalin' },
//   { value: 'Fili' },
//   { value: 'Kili' },
//   { value: 'Gorbag' },
//   { value: 'Shagrat' },
//   { value: 'Anarion' },
// ]

