const regions = [
  { value: 'Minas Tirith', coords: [1696.3132, 1183.6707] },
  { value: 'Edoras', coords: [1411.6403, 1038.0861] },
  { value: `Helm's Deep`, coords: [1354.0849, 1003.2273] },
  { value: 'Osgiliath', coords: [1739.1387, 1171.8463] },
  { value: 'Angmar', coords: [1294.9082, 239.5778] },
  { value: 'Mount Gundabad', coords: [1401.102, 242.0098] },
  { value: 'Tolfalas', coords: [1449.4142, 1415.677] },
  { value: 'Dol Guldur', coords: [1621.6751, 690.1289] },
  { value: 'Hills of Evendim', coords: [817.1153, 294.9281] },
  { value: 'Weathertop', coords: [1142.0203, 457.9452] },
  { value: 'Lindon', coords: [-1, -1] },
  { value: 'Rivendell', coords: [1398.1824, 448.2172] },
  { value: 'Erebor', coords: [1784.0469, 313.6463] },
  { value: 'Shire', coords: [833.9935, 514.8544] },
  { value: 'Numenor', coords: [-1, -1] },
  { value: 'Havens of Sirion', coords: [-1, -1] },
  { value: 'Rohan', coords: [1433.8505, 954.0742] },
  { value: 'Lothlorien', coords: [1433.4286, 725.3515] },
  { value: 'Valinor', coords: [-1, -1] },
  { value: 'The Woodland Realm', coords: [1710.9432, 333.9389] },
  { value: 'Gondolin', coords: [-1, -1] },
  { value: 'Hobbiton', coords: [876.1305, 480.644] },
  { value: 'Isengard', coords: [1237.7246, 913.8391] },
  { value: 'Bree', coords: [1040.155, 488.7723] },
  { value: 'Carn Dum', coords: [1159.1567, 160.4307] },
  { value: 'Iron Hills', coords: [2038.7968, 348.9183] },
  { value: 'Lake Town', coords: [1766.0946, 354.9338] },
  { value: 'Fangorn', coords: [1373.0826, 860.2411] },
  { value: 'Barad Dur', coords: [1930.518, 1108.8843] },
  { value: 'Minas Morgul', coords: [1814.961, 1171.443] },
  { value: 'Arnor', coords: [979.2904, 206.8163] },
];

export const sortedRegions = regions.sort((a, b) => a.value.localeCompare(b.value));

export const pages = [
  { value: 'westron' },
  { value: 'sindarin' },
  { value: 'khuzdul' },
  { value: 'black speech' },
  { value: 'aduanic' },
  { value: 'quenya' },
  { value: 'telerin' },
  { value: 'men' },
  { value: 'elf' },
  { value: 'dwarf' },
  { value: 'hobbit' },
  { value: 'orc' },
  { value: 'barlog' },
  { value: 'dragon' },
  { value: 'ainur' },
  { value: 'Rohirrim' },
  { value: 'Gondorians' },
  { value: 'Numenorians' },
  { value: 'Arnorians' },
  { value: 'Dalesmen' },
  { value: 'Noldor' },
  { value: 'Sindar' },
  { value: 'Teleri' },
  { value: 'Silvan' },
  { value: 'LongBeards' },
  { value: 'Firebeards' },
  { value: 'Broadbeams' },
  { value: 'Ironfists' },
  { value: 'Mordor-Orc' },
  { value: 'Misty-Mountain-Orc' },
  { value: 'Moria-Orc' },
  { value: 'Harfoots' },
  { value: 'Stoors' },
  { value: 'Fallohides' },
  { value: 'Valar' },
  { value: 'Maiar' },
  { value: 'Minas-Tirith' },
  { value: 'Edoras' },
  { value: `Helm's-Deep` },
  { value: 'Osgilath' },
  { value: 'Angmar' },
  { value: 'Mount-Gundabasd' },
  { value: 'Tolfalas' },
  { value: 'Dol-Guldur' },
  { value: 'Hills-of-Evendim' },
  { value: 'Weathertop' },
  { value: 'Lindon' },
  { value: 'Rivendell' },
  { value: 'Erebor' },
  { value: 'Shire' },
  { value: 'Numenor' },
  { value: 'Havens-of-Sirion' },
  { value: 'Rohan' },
  { value: 'Lothlorien' },
  { value: 'Valinor' },
  { value: 'The-Woodland-Realm' },
  { value: 'Gondolin' },
  { value: 'Hobbiton' },
  { value: 'Isengard' },
  { value: 'Bree' },
  { value: 'Carn-Dum' },
  { value: 'Iron-Hills' },
  { value: 'Lake-Town' },
  { value: 'Fangorn' },
  { value: 'Barad-dûr' },
  { value: 'Minas-Morgul' },
  { value: 'Arnor' },
  { value: 'Moria' },
  { value: 'Aragorn-II' },
  { value: 'Arwen-Undomiel' },
  { value: 'Boromir' },
  { value: 'Faramir' },
  { value: 'Denethor II' },
  { value: 'Theoden' },
  { value: 'Gimli' },
  { value: 'Frodo-Baggins' },
  { value: 'Gandalf' },
  { value: 'Elendil' },
  { value: 'Isildur' },
  { value: 'Elrond' },
  { value: 'Eomer' },
  { value: 'Haldir' },
  { value: 'Galadriel' },
  { value: 'Celeborn' },
  { value: 'Sauron' },
  { value: 'Melkor' },
  { value: 'Azog' },
  { value: 'Legolas' },
  { value: 'Thranduil' },
  { value: 'Eärendil' },
  { value: 'Elros' },
  { value: 'Thorin-II' },
  { value: 'Eowyn' },
  { value: 'Grima' },
  { value: 'Theodred' },
  { value: 'King-Helm' },
  { value: 'Eorl' },
  { value: 'Witch-King-of-Angmar' },
  { value: 'Balin' },
  { value: 'Dwalin' },
  { value: 'Fili' },
  { value: 'Kili' },
  { value: 'Gorbag' },
  { value: 'Shagrat' },
  { value: 'Anarion' },
]

